#Requires -Version 5.1
<#
.SYNOPSIS
    codebase-memory-mcp 软件配套脚本，可手动执行、Agent调用
    Git 仓库一键扫描注册工具 — 扫描指定目录树，发现新 git 仓库并自动注册。
    安全加固版 v2.1.0 — 修复命令注入、超时孤儿进程、大小写敏感、正则误匹配等高危/中危问题。

.DESCRIPTION
    递归扫描指定目录树（默认 3 层深度），发现其中所有 git 仓库。
    与已注册记录比对后，对未注册的仓库自动调用双通道注册
    （dmcp HTTP API 优先，CLI 直接调用备选）。

    运行方式：
        # 基础运行（无日志）
        PowerShell -ExecutionPolicy Bypass -File watch_git_repos.ps1

        # 带日志（日志写入脚本所在目录）
        PowerShell -ExecutionPolicy Bypass -File watch_git_repos.ps1 -Log

        # 窗口最小化运行
        PowerShell -ExecutionPolicy Bypass -File watch_git_repos.ps1 -Log -Minimize

    执行完毕后窗口自动关闭，执行结果以 JSON 格式输出到 stdout
    和脚本所在目录的 .last_result.json（供 Agent 读取）。

.PARAMETER Log
    若指定，在脚本所在目录写出 watch_git_repos.log 日志文件。

.PARAMETER Minimize
    若指定，执行期间 PowerShell 窗口最小化。

.NOTES
    Author:  zhangweildlh (auto-generated by WorkBuddy)
    Date:    2026-09-04
    Version: 2.1.0 (安全加固版)
#>

[CmdletBinding()]
param(
    [switch]$Log,
    [switch]$Minimize
)

# -- 严格模式：禁用（PS 5.1 兼容性问题，变量检查由代码逻辑保证）--
# Set-StrictMode -Version 1.0

# ============================================================
# █ 用户配置区（所有参数变量化，修改此处即可适配你的环境）
# ============================================================

# -- 扫描目录列表（随意添加/删除，每行一个绝对路径） --
$script:ScanRoots = @(
    "D:\Documents\AI_Work_Temp"
    # 在此添加更多扫描根目录，例如：
    # "D:\Documents\AI_MCP-Skill-CLI"
    # "D:\Projects"
)

# -- 递归扫描深度（0=仅当前目录直接子项，1=再深一层，以此类推） --
$script:ScanDepth = 3

# -- 忽略的目录名（精确匹配目录名，非正则。这些目录下的 .git 不会触发注册） --
$script:IgnoreDirNames = @(
    'node_modules'
    '.cache'
    '__pycache__'
    '.venv'
    'venv'
    '.tox'
    '.eggs'
    'site-packages'
    '.claude-worktrees'
    '.worktrees'
    '.vscode'
    '.idea'
)

# -- dmcp HTTP API 地址（dmcp 服务运行在本地时使用） --
$script:DmcpUrl = "http://127.0.0.1:8082"

# -- codebase-memory-mcp CLI 完整路径（dmcp 不可用时的备选） --
# 如果已加入系统 PATH，可只写文件名；否则写绝对路径。
$script:CbmCliPath = "codebase-memory-mcp"

# -- 注册模式（moderate / full / fast） --
$script:IndexMode = "moderate"

# -- 状态文件路径（记录已注册的仓库，避免重复注册） --
# 默认在脚本所在目录下，一般无需修改。
$script:StateFile = Join-Path $PSScriptRoot ".watch_git_repos_state.json"

# ============================================================
# █ 实现区
# ============================================================

# -- 脚本所在目录 --
$script:ScriptDir = $PSScriptRoot
if (-not $script:ScriptDir) { $script:ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path }
if (-not $script:ScriptDir) { $script:ScriptDir = Get-Location }

# -- 日志文件路径（仅当 -Log 开关指定时生效） --
$script:LogFile = if ($Log) { Join-Path $script:ScriptDir "watch_git_repos.log" } else { $null }

# -- 结果文件路径（供 Agent 读取） --
$script:ResultFile = Join-Path $script:ScriptDir ".last_result.json"

# -- 互斥锁名称（防止并发运行冲突） --
$script:MutexName = "Global\WatchGitRepos_$(($script:ScriptDir -replace '[^\w]', '_'))"

# -- 执行结果收集器（使用 List 替代数组 += 提升性能） --
$script:Result = @{
    start_time   = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    scan_roots   = $script:ScanRoots
    scan_depth   = $script:ScanDepth
    scanned      = [System.Collections.Generic.List[string]]::new()
    new_repos    = [System.Collections.Generic.List[string]]::new()
    registered   = [System.Collections.Generic.List[string]]::new()
    failed       = [System.Collections.Generic.List[string]]::new()
    skipped      = [System.Collections.Generic.List[string]]::new()
    total_found  = 0
    total_new    = 0
    total_reg    = 0
    total_fail   = 0
    total_skip   = 0
    end_time     = $null
    duration_ms  = 0
    status       = "running"
}

# -- 日志函数 --
function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $line = "[$ts] [$Level] $Message"
    if ($script:LogFile) {
        try {
            Add-Content -Path $script:LogFile -Value $line -Encoding UTF8
        } catch {
            # 日志写入失败不中断脚本
        }
    }
}

# -- 检查路径是否应被忽略（精确目录名匹配，非正则子串匹配） --
function Test-IgnoredPath {
    param([string]$Path)
    # 将路径拆分为各段目录名，精确匹配
    $segments = $Path -split '[\\/]'
    foreach ($ign in $script:IgnoreDirNames) {
        if ($segments -contains $ign) { return $true }
    }
    return $false
}

# -- 已注册状态（脚本级变量，避免 PS 5.1 函数返回值问题） --
$script:RegisteredState = @{}  # Hashtable，忽略大小写

# -- 加载已注册状态（忽略大小写，Windows 路径不区分大小写） --
function Load-RegisteredState {
    param()
    $script:RegisteredState = @{}
    if (Test-Path $script:StateFile) {
        try {
            $json = Get-Content $script:StateFile -Raw -Encoding UTF8 -ErrorAction Stop
            if ($json) {
                $arr = $json | ConvertFrom-Json -ErrorAction Stop
                if ($arr -is [array]) {
                    foreach ($item in $arr) { $script:RegisteredState[$item] = $true }
                }
            }
        } catch {
            Write-Log "读取状态文件失败: $($_.Exception.Message)" "ERROR"
        }
    }
}

# -- 保存已注册状态（带错误处理） --
function Save-RegisteredState {
    param()
    try {
        $keys = @($script:RegisteredState.Keys) | ConvertTo-Json -Compress
        Set-Content -Path $script:StateFile -Value $keys -Encoding UTF8 -ErrorAction Stop
    } catch {
        Write-Log "保存状态文件失败: $($_.Exception.Message)" "ERROR"
    }
}

# -- 验证是否为合法 git 仓库 --
function Test-GitRepoValid {
    param([string]$RepoPath)
    try {
        $gitDir = Join-Path $RepoPath ".git"
        # .git 必须是目录（而非文件），且包含必要文件
        if (-not (Test-Path $gitDir -PathType Container)) { return $false }
        $headFile = Join-Path $gitDir "HEAD"
        if (-not (Test-Path $headFile)) { return $false }
        return $true
    } catch {
        return $false
    }
}

# -- 双通道注册：dmcp HTTP 优先，CLI 备选 --
function Invoke-RegisterRepo {
    param([string]$RepoPath)

    # 通道 1：dmcp HTTP API
    try {
        $body = @{
            name      = "index_repository"
            arguments = @{
                repo_path = $RepoPath
                mode      = $script:IndexMode
            }
        } | ConvertTo-Json -Compress -Depth 5

        $resp = Invoke-RestMethod -Uri "$script:DmcpUrl/dynamic-mcp/call_tool" `
            -Method POST -Body $body -ContentType "application/json" `
            -TimeoutSec 120 -ErrorAction Stop

        # 检查响应体中的业务状态（HTTP 200 未必代表业务成功）
        if ($resp.success -eq $false) {
            $errMsg = if ($resp.error) { $resp.error } else { "业务返回 success=false" }
            Write-Log "dmcp HTTP 业务失败: $errMsg" "WARN"
            # 继续降级走 CLI
        } else {
            return @{ success = $true; channel = "dmcp_http"; response = $resp }
        }
    } catch {
        Write-Log "dmcp HTTP 注册失败: $($_.Exception.Message)" "WARN"
    }

    # 通道 2：CLI 直接调用（使用 ConvertTo-Json 安全生成参数，杜绝手动拼接）
    # 先检查 CLI 是否可用
    $cliCmd = Get-Command $script:CbmCliPath -ErrorAction SilentlyContinue
    if (-not $cliCmd) {
        return @{ success = $false; channel = "cli"; error = "CLI 未找到: $($script:CbmCliPath)，请确认已加入 PATH 或填写绝对路径" }
    }

    try {
        # 使用 ConvertTo-Json 安全生成 JSON，杜绝命令注入
        $payload = @{
            repo_path = $RepoPath
            mode      = $script:IndexMode
        } | ConvertTo-Json -Compress

        # 使用 Start-Process -ArgumentList 数组形式，自动处理所有转义（含路径中的 \ / " 等）
        $proc = Start-Process -FilePath $cliCmd.Source `
            -ArgumentList @("cli", "index_repository", $payload) `
            -WorkingDirectory $script:ScriptDir `
            -RedirectStandardOutput "$($script:ScriptDir)\.cli_stdout.tmp" `
            -RedirectStandardError "$($script:ScriptDir)\.cli_stderr.tmp" `
            -NoNewWindow -PassThru

        # 等待进程退出（120秒超时），超时则终止防止孤儿进程
        $exited = $proc.WaitForExit(120000)
        if (-not $exited) {
            try { $proc.Kill() } catch {}
            return @{ success = $false; channel = "cli"; error = "CLI 执行超时(120s)，已强制终止" }
        }

        if ($proc.ExitCode -eq 0) {
            return @{ success = $true; channel = "cli" }
        } else {
            $err = ""
            if (Test-Path "$($script:ScriptDir)\.cli_stderr.tmp") {
                $err = Get-Content "$($script:ScriptDir)\.cli_stderr.tmp" -Raw -ErrorAction SilentlyContinue
            }
            return @{ success = $false; channel = "cli"; error = $err }
        }
    } catch {
        return @{ success = $false; channel = "cli"; error = $_.Exception.Message }
    } finally {
        # 清理临时输出文件
        Remove-Item "$($script:ScriptDir)\.cli_stdout.tmp" -ErrorAction SilentlyContinue
        Remove-Item "$($script:ScriptDir)\.cli_stderr.tmp" -ErrorAction SilentlyContinue
    }
}

# -- 扫描单个目录树 --
function Scan-DirectoryTree {
    param([string]$RootPath)

    $found = [System.Collections.Generic.List[string]]::new()

    if (-not (Test-Path $RootPath)) {
        Write-Log "目录不存在，跳过: $RootPath" "WARN"
        return $found
    }

    Write-Log "开始扫描: $RootPath (深度: $($script:ScanDepth))" "INFO"

    try {
        # 使用 -Depth 参数控制递归层数
        $gitDirs = Get-ChildItem -Path $RootPath -Recurse -Filter ".git" `
            -Directory -Depth $script:ScanDepth -ErrorAction SilentlyContinue

        foreach ($gd in $gitDirs) {
            # 从 .git 路径提取仓库根目录（.git 为4字符，加上前面的 \ 共5字符）
            $repoRoot = $gd.FullName.Substring(0, $gd.FullName.Length - 5).TrimEnd('\', '/')

            if (Test-IgnoredPath -Path $repoRoot) {
                Write-Log "忽略匹配目录: $repoRoot" "INFO"
                $script:Result.skipped.Add($repoRoot) | Out-Null
                continue
            }

            # 验证是否为合法 git 仓库（而非空目录）
            if (-not (Test-GitRepoValid -RepoPath $repoRoot)) {
                Write-Log "跳过无效 git 仓库: $repoRoot" "INFO"
                $script:Result.skipped.Add($repoRoot) | Out-Null
                continue
            }

            $found.Add($repoRoot) | Out-Null
        }
    } catch {
        Write-Log "扫描异常 ($RootPath): $($_.Exception.Message)" "ERROR"
    }

    Write-Log "扫描完成: $RootPath, 发现 $($found.Count) 个仓库" "INFO"
    return $found
}

# -- 最小化当前 PowerShell 窗口（使用 GetConsoleWindow 替代 FindWindow） --
function Minimize-CurrentWindow {
    try {
        $code = @'
using System;
using System.Runtime.InteropServices;
public class Win32 {
    [DllImport("kernel32.dll")] public static extern IntPtr GetConsoleWindow();
    [DllImport("user32.dll")] public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);
    public const int SW_MINIMIZE = 6;
    public static void Minimize() {
        var hWnd = GetConsoleWindow();
        if (hWnd != IntPtr.Zero) ShowWindow(hWnd, SW_MINIMIZE);
    }
}
'@
        Add-Type -TypeDefinition $code -ErrorAction Stop
        [Win32]::Minimize()
    } catch {
        Write-Log "最小化窗口失败: $($_.Exception.Message)" "DEBUG"
    }
}

# -- 输出结果（JSON 格式，供 Agent 读取） --
function Output-Result {
    $script:Result.end_time = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $script:Result.total_found = $script:Result.scanned.Count
    $script:Result.total_new = $script:Result.new_repos.Count
    $script:Result.total_reg = $script:Result.registered.Count
    $script:Result.total_fail = $script:Result.failed.Count
    $script:Result.total_skip = $script:Result.skipped.Count
    $script:Result.status = if ($script:Result.total_fail -gt 0) { "partial_success" } else { "success" }

    # 将 List 转为数组再序列化
    $output = @{
        start_time   = $script:Result.start_time
        scan_roots   = $script:Result.scan_roots
        scan_depth   = $script:Result.scan_depth
        scanned      = @($script:Result.scanned)
        new_repos    = @($script:Result.new_repos)
        registered   = @($script:Result.registered)
        failed       = @($script:Result.failed)
        skipped      = @($script:Result.skipped)
        total_found  = $script:Result.total_found
        total_new    = $script:Result.total_new
        total_reg    = $script:Result.total_reg
        total_fail   = $script:Result.total_fail
        total_skip   = $script:Result.total_skip
        end_time     = $script:Result.end_time
        duration_ms  = $script:Result.duration_ms
        status       = $script:Result.status
    }

    $json = $output | ConvertTo-Json -Depth 5 -Compress

    # 写入结果文件（带错误处理）
    try {
        Set-Content -Path $script:ResultFile -Value $json -Encoding UTF8 -ErrorAction Stop
    } catch {
        Write-Log "写入结果文件失败: $($_.Exception.Message)" "ERROR"
    }

    # 输出到 stdout（Agent 可读）
    Write-Output $json
}

# ============================================================
# █ 主程序
# ============================================================

$stopwatch = [System.Diagnostics.Stopwatch]::StartNew()

# 互斥锁：防止并发运行导致状态文件冲突
$mutex = New-Object System.Threading.Mutex($false, $script:MutexName)
$gotLock = $false
try {
    $gotLock = $mutex.WaitOne(1000)
    if (-not $gotLock) {
        Write-Log "另一个实例正在运行，本次执行退出" "WARN"
        $mutex.Dispose()
        # 输出错误结果
        @{
            status = "error"
            error  = "另一个实例正在运行，本次执行退出"
        } | ConvertTo-Json -Compress
        exit 1
    }
} catch {
    # 互斥锁创建失败不阻塞，继续执行
    Write-Log "互斥锁创建失败: $($_.Exception.Message)" "WARN"
}

try {
    # 最小化窗口
    if ($Minimize) { Minimize-CurrentWindow }

    Write-Log "=== Git 仓库扫描注册开始 ===" "INFO"
    Write-Log "扫描深度: $($script:ScanDepth), 根目录数: $($script:ScanRoots.Count)" "INFO"

    # 前置校验：检查扫描根目录是否存在
    $validRoots = @()
    foreach ($root in $script:ScanRoots) {
        if (Test-Path $root) {
            $validRoots += $root
        } else {
            Write-Log "扫描根目录不存在，跳过: $root" "WARN"
        }
    }
    if ($validRoots.Count -eq 0) {
        Write-Log "没有有效的扫描根目录，退出" "ERROR"
        $script:Result.status = "error"
        $script:Result.end_time = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        $script:Result.duration_ms = $stopwatch.ElapsedMilliseconds
        Output-Result
        exit 1
    }

    # 加载已注册状态
    Load-RegisteredState
    Write-Log "已注册仓库数: $($script:RegisteredState.Count)" "INFO"

    # 扫描所有目录
    $allFound = [System.Collections.Generic.List[string]]::new()
    foreach ($root in $validRoots) {
        $repos = Scan-DirectoryTree -RootPath $root
        foreach ($r in $repos) { $allFound.Add($r) | Out-Null }
    }

    $script:Result.scanned = $allFound
    Write-Log "扫描完成，共发现 $($allFound.Count) 个仓库" "INFO"

    # 筛选新仓库
    $newRepos = [System.Collections.Generic.List[string]]::new()
    foreach ($repo in $allFound) {
        if (-not $script:RegisteredState.ContainsKey($repo)) {
            $newRepos.Add($repo) | Out-Null
        }
    }
    $script:Result.new_repos = $newRepos
    Write-Log "新仓库数: $($newRepos.Count)" "INFO"

    # 注册新仓库
    foreach ($repo in $newRepos) {
        Write-Log "注册: $repo" "INFO"
        $regResult = Invoke-RegisterRepo -RepoPath $repo
        if ($regResult.success) {
            Write-Log "注册成功 [$($regResult.channel)]: $repo" "INFO"
            $script:Result.registered.Add($repo) | Out-Null
            $script:RegisteredState[$repo] = $true
        } else {
            Write-Log "注册失败: $($regResult.error)" "ERROR"
            $script:Result.failed.Add($repo) | Out-Null
        }
    }

    # 保存状态
    Save-RegisteredState

    $stopwatch.Stop()
    $script:Result.duration_ms = $stopwatch.ElapsedMilliseconds

    # 输出结果
    Output-Result

    Write-Log "=== 扫描注册完成 ($($stopwatch.ElapsedMilliseconds)ms) ===" "INFO"

} finally {
    # 释放互斥锁
    if ($gotLock) {
        try { $mutex.ReleaseMutex() } catch {}
    }
    $mutex.Dispose()
}
