#Requires -Version 5.1
<#
.SYNOPSIS
    codebase-memory-mcp 软件配套脚本，可手动执行、Agent调用
    Git 仓库一键扫描注册工具 — 扫描指定目录树，发现新 git 仓库并自动注册。
    安全加固版 v2.4.0 — 三轮审计共修复 24 项问题（命令注入、超时孤儿进程、大小写敏感、正则误匹配、
    白名单语义校验、路径标准化、互斥锁防碰撞、退出码约定、dmcp 端口参数化、exe 通道看门狗与缓存目录身份校验、
    Process 通道孤儿进程/性能、Minimize 类型检查、路径通配符/符号链接副作用等）。

.DESCRIPTION
    递归扫描指定目录树（默认 3 层深度），发现其中所有 git 仓库。
    与已注册记录比对后，对未注册的仓库自动调用双通道注册
    （dmcp HTTP API 优先，CLI 直接调用备选）。

    运行方式：
        # 基础运行（无日志）
        PowerShell -ExecutionPolicy Bypass -File watch_git_repos.ps1

        # 带日志（日志写入脚本所在目录）
        PowerShell -ExecutionPolicy Bypass -File watch_git_repos.ps1 -Log

        # 窗口最小化运行
        PowerShell -ExecutionPolicy Bypass -File watch_git_repos.ps1 -Log -Minimize

    执行完毕后窗口自动关闭，执行结果以 JSON 格式输出到 stdout
    和脚本所在目录的 .last_result.json（供 Agent 读取）。

.PARAMETER Log
    若指定，在脚本所在目录写出 watch_git_repos.log 日志文件。

.PARAMETER Minimize
    若指定，执行期间 PowerShell 窗口最小化。

.NOTES
    Author:  zhangweildlh (auto-generated by WorkBuddy)
    Date:    2026-09-04
    Version: 2.4.0 (第三轮审计修复 + Process 通道重构版)
#>

[CmdletBinding()]
param(
    [switch]$Log,
    [switch]$Minimize
)

# -- 严格模式：禁用（PS 5.1 兼容性问题，变量检查由代码逻辑保证）--
# Set-StrictMode -Version 1.0

# ============================================================
# █ 用户配置区（所有参数变量化，修改此处即可适配你的环境）
# ============================================================

# -- 扫描目录列表（随意添加/删除，每行一个绝对路径） --
$script:ScanRoots = @(
    "D:\Documents\AI_MCP-Skill-CLI"
    "D:\Documents\AI_Work_Temp"
    # 在此添加更多扫描根目录，例如：
    # "D:\Projects"
)

# -- 递归扫描深度（0=仅当前目录直接子项，1=再深一层，以此类推） --
# 必须为 0-10 范围内的整数，超出范围将报错退出
$script:ScanDepth = 3

# -- 忽略的目录名（精确匹配目录名，非正则。这些目录下的 .git 不会触发注册） --
$script:IgnoreDirNames = @(
    'node_modules'
    '.cache'
    '__pycache__'
    '.venv'
    'venv'
    '.tox'
    '.eggs'
    'site-packages'
    '.claude-worktrees'
    '.worktrees'
    '.vscode'
    '.idea'
    '.workbuddy'
    'docs'
    '_gsdata_'
)

# -- dmcp HTTP API 基础地址（dmcp 服务运行在本地时使用） --
# 注意：dmcp 使用标准 MCP JSON-RPC 2.0 协议，路径为 /dynamic-mcp，
#       调用方法为 tools/call，而非 /dynamic-mcp/call_tool。
$script:DmcpBaseUrl = "http://127.0.0.1:8082/dynamic-mcp"

# -- dmcp HTTP API 地址（兼容旧版，保留但不使用） --
$script:DmcpUrl = $script:DmcpBaseUrl

# -- codebase-memory-mcp 可执行文件路径（与脚本同目录，不依赖 PATH） --
# dmcp HTTP 不可用时的备选通道：直接调用同目录下的 codebase-memory-mcp.exe
# 的 CLI 模式执行 index_repository。
$script:CbmExePath = Join-Path $PSScriptRoot "codebase-memory-mcp.exe"
# 缓存目录路径必须用正斜杠（/）：cbm 用 SHA256 校验缓存目录身份，反斜杠与正斜杠算出的哈希不同。
# Join-Path 在 Windows 上默认产出反斜杠，这里统一转成正斜杠，避免与 cbm 守护进程（已用正斜杠初始化）的哈希对不上。
# 实测：SHA256("D:/codebase-memory-mcp/data") = d91b00c9...（守护进程活跃缓存），
#       SHA256("D:\codebase-memory-mcp\data") = aabaa08b...（不匹配，报 cache-private）。
# 仅替换分隔符即可满足 cbm 要求（驱动器号 D: + 正斜杠路径 D:/... 与守护进程一致，已端到端验证 7/7 成功）。
# 若部署在 UNC 路径（\\server\share），替换后会变成 //server/share，此时需另行适配——当前默认本地目录部署不涉及。
$script:CbmCacheDir = (Join-Path $PSScriptRoot "data").Replace('\', '/')

# -- 注册模式（moderate / full / fast） --
$script:IndexMode = "full"

# -- 路径安全白名单（可选，留空表示不限制） --
# 扫描出的仓库路径必须匹配以下前缀之一才允许注册；留空 = 不限制。
$script:PathWhitelist = @(
    # "D:\Documents\AI_Work_Temp"
    # "D:\Projects"
)

# -- 状态文件路径（记录已注册的仓库，避免重复注册） --
# 默认在脚本所在目录下，一般无需修改。
$script:StateFile = Join-Path $PSScriptRoot ".watch_git_repos_state.json"

# ============================================================
# █ 实现区
# ============================================================

# -- 脚本所在目录 --
$script:ScriptDir = $PSScriptRoot
if (-not $script:ScriptDir) { $script:ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path }
if (-not $script:ScriptDir) { $script:ScriptDir = Get-Location }

# -- 日志文件路径（仅当 -Log 开关指定时生效） --
$script:LogFile = if ($Log) { Join-Path $script:ScriptDir "watch_git_repos.log" } else { $null }

# -- 结果文件路径（供 Agent 读取） --
$script:ResultFile = Join-Path $script:ScriptDir ".last_result.json"

# -- 互斥锁名称（防止并发运行冲突） --
# 注意：使用 Local\ 命名空间（非 Global\），避免因管理员权限要求导致锁创建失败。
# Global\ 命名空间需要管理员权限才能创建/访问。
# 后缀使用 ScriptDir 的 SHA1 哈希前 8 位，消除路径转下划线后的碰撞风险。
$_sha1 = [System.Security.Cryptography.SHA1]::Create()
$_hashBytes = $_sha1.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($script:ScriptDir))
$_sha1.Dispose()
$_mutexSuffix = [System.BitConverter]::ToString($_hashBytes).Replace('-', '').Substring(0, 8)
$script:MutexName = "Local\WatchGitRepos_$_mutexSuffix"

# -- 执行结果收集器（使用 List 替代数组 += 提升性能） --
$script:Result = @{
    start_time   = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    scan_roots   = $script:ScanRoots
    scan_depth   = $script:ScanDepth
    scanned      = [System.Collections.Generic.List[string]]::new()
    new_repos    = [System.Collections.Generic.List[string]]::new()
    registered   = [System.Collections.Generic.List[string]]::new()
    failed       = [System.Collections.Generic.List[string]]::new()
    skipped      = [System.Collections.Generic.List[string]]::new()
    total_found  = 0
    total_new    = 0
    total_reg    = 0
    total_fail   = 0
    total_skip   = 0
    end_time     = $null
    duration_ms  = 0
    status       = "running"
}

# -- 日志函数 --
function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    # 过滤控制字符（换行、回车、制表符以外的 ASCII 控制字符），防止日志注入
    $safeMsg = if ($Message) {
        # 过滤所有 ASCII 控制字符（含 \x0A LF、\x0D CR），防止日志注入
        [regex]::Replace($Message, '[\x00-\x1F\x7F]', '·')
    } else { "" }
    $line = "[$ts] [$Level] $safeMsg"
    if ($script:LogFile) {
        try {
            Add-Content -Path $script:LogFile -Value $line -Encoding UTF8
        } catch {
            # 日志写入失败时输出到 stdout，不静默吞掉
            Write-Host "[$ts] [ERROR] 日志写入失败: $($_.Exception.Message)"
        }
    }
}

# -- 检查路径是否应被忽略（精确目录名匹配，非正则子串匹配） --
function Test-IgnoredPath {
    param([string]$Path)
    # 将路径拆分为各段目录名，精确匹配
    $segments = $Path -split '[\\/]'
    foreach ($ign in $script:IgnoreDirNames) {
        if ($segments -contains $ign) { return $true }
    }
    return $false
}

# -- 已注册状态（脚本级变量，避免 PS 5.1 函数返回值问题） --
$script:RegisteredState = @{}  # Hashtable，忽略大小写

# -- 加载已注册状态（忽略大小写，Windows 路径不区分大小写） --
function Load-RegisteredState {
    param()
    $script:RegisteredState = @{}
    if (Test-Path $script:StateFile) {
        try {
            $json = Get-Content $script:StateFile -Raw -Encoding UTF8 -ErrorAction Stop
            if ($json) {
                $arr = $json | ConvertFrom-Json -ErrorAction Stop
                if ($arr -is [array]) {
                    foreach ($item in $arr) {
                        # 严格校验元素类型：仅接受字符串键，拒绝数字/对象/嵌套结构
                        if ($item -is [string]) {
                            $script:RegisteredState[$item] = $true
                        } else {
                            Write-Log "状态文件包含非字符串元素，已跳过: $($item | ConvertTo-Json -Compress)" "WARN"
                        }
                    }
                }
            }
        } catch {
            Write-Log "读取状态文件失败: $($_.Exception.Message)" "ERROR"
        }
    }
}

# -- 保存已注册状态（带错误处理） --
function Save-RegisteredState {
    param()
    try {
        $keys = @($script:RegisteredState.Keys) | ConvertTo-Json -Compress
        Set-Content -Path $script:StateFile -Value $keys -Encoding UTF8 -ErrorAction Stop
    } catch {
        Write-Log "保存状态文件失败: $($_.Exception.Message)" "ERROR"
    }
}

# -- 语义化子目录校验：判断 $ChildPath 是否为 $ParentPath 的子目录 --
# 使用 [System.IO.Path]::GetFullPath() 做纯字符串规范化 + 末尾追加 '\' + StartsWith，
# 杜绝前缀字符串误匹配、-like 通配符语义，以及 Resolve-Path 的两个副作用：
#   1. Resolve-Path 会解释通配符（* ? [ ]），含方括号的合法目录名可能导致多结果或失败
#   2. Resolve-Path 会解析符号链接，白名单路径是符号链接时解析后字符串与配置不同，造成误拒
# GetFullPath 不解析通配符也不解析符号链接，仅做绝对路径与分隔符归一化，语义更可控。
function Test-IsSubDirectory {
    param([string]$ChildPath, [string]$ParentPath)
    try {
        $childFull  = [System.IO.Path]::GetFullPath($ChildPath).TrimEnd('\', '/')
        $parentFull = [System.IO.Path]::GetFullPath($ParentPath).TrimEnd('\', '/') + '\'
        return $childFull.StartsWith($parentFull, [System.StringComparison]::OrdinalIgnoreCase)
    } catch {
        # 路径包含非法字符等极端情况：保守起见拒绝访问，不回退到可能被绕过的字符串前缀匹配
        return $false
    }
}

# -- 验证是否为合法 git 仓库 --
function Test-GitRepoValid {
    param([string]$RepoPath)
    try {
        $gitDir = Join-Path $RepoPath ".git"
        # .git 必须是目录（而非文件），且包含必要文件
        if (-not (Test-Path $gitDir -PathType Container)) { return $false }
        $headFile = Join-Path $gitDir "HEAD"
        if (-not (Test-Path $headFile)) { return $false }
        return $true
    } catch {
        return $false
    }
}

# -- 双通道注册：dmcp HTTP 优先，CLI 备选 --
function Invoke-RegisterRepo {
    param([string]$RepoPath)

    # 通道 1：dmcp HTTP API（标准 MCP JSON-RPC 2.0 协议）
    try {
        # dmcp 暴露的是标准 MCP Streamable HTTP 端点，使用 JSON-RPC 2.0 格式：
        #   method: "tools/call"
        #   params: { name, arguments }
        # 而非旧版的 /dynamic-mcp/call_tool + { name, arguments } 格式
        $body = @{
            jsonrpc = "2.0"
            id      = 1
            method  = "tools/call"
            params  = @{
                name      = "index_repository"
                arguments = @{
                    repo_path = $RepoPath
                    mode      = $script:IndexMode
                }
            }
        } | ConvertTo-Json -Compress -Depth 5

        $resp = Invoke-RestMethod -Uri $script:DmcpBaseUrl `
            -Method POST -Body $body -ContentType "application/json" `
            -TimeoutSec 120 -ErrorAction Stop

        # 检查响应体中的业务状态（HTTP 200 未必代表业务成功）
        # 标准 JSON-RPC 响应：{ jsonrpc, id, result } 或 { jsonrpc, id, error }
        if ($resp.error) {
            $errMsg = if ($resp.error.message) { $resp.error.message } else { $resp.error | ConvertTo-Json -Compress }
            Write-Log "dmcp HTTP 业务失败: $errMsg" "WARN"
            # 继续降级走 CLI
        } else {
            return @{ success = $true; channel = "dmcp_http"; response = $resp.result }
        }
    } catch {
        Write-Log "dmcp HTTP 注册失败: $($_.Exception.Message)" "WARN"
    }

    # 通道 2：直接调用同目录下的 codebase-memory-mcp.exe CLI
    # 先检查可执行文件是否存在
    if (-not (Test-Path $script:CbmExePath)) {
        return @{ success = $false; channel = "exe"; error = "codebase-memory-mcp.exe 未找到: $($script:CbmExePath)" }
    }

    try {
        # 使用 --repo-path 和 --mode 参数直接调用（非 JSON body，避免路径转义问题）
        # PS 5.1 的 Start-Process 会因环境变量字典大小写冲突（Path vs PATH）报 "已添加项" 错误，
        # 因此不能使用 Start-Process。改用 System.Diagnostics.Process 直接启动外部程序：
        #   - 绕开 Start-Process 的环境变量字典冲突 bug
        #   - 比 Start-Job 轻量：无需额外启动 powershell.exe 进程（Start-Job 每次
        #     调用都新建一个 powershell.exe，数百毫秒至数秒开销，7 仓库串行累计显著延迟）
        #   - 超时后可调用 Kill(true) 精确杀死进程树，无孤儿进程残留
        #     （Start-Job + Stop-Job 只杀 Job runspace，不杀 Job 内启动的 exe 子进程）
        #   - ExitCode 属于 Process 对象本身，可靠读取（不像 $job.ExitCode 恒为 $null）
        #   - RedirectStandardOutput/Error + ReadToEnd 可靠捕获输出（不像 Start-Job
        #     需要临时文件中转，且 stderr 经 & 会触发 RemoteExceptions 冒泡）
        # 注意：.NET Framework (PS 5.1) 的 ProcessStartInfo 没有 EnvironmentVariables 属性
        # （那是 .NET Core 才有的），改用父作用域 $env:CBM_CACHE_DIR —— Process.Start()
        # 默认继承父进程环境块，因此把变量设在父作用域即可传给子进程。用 try/finally 恢复
        # 原值，避免污染同一会话中后续其他操作。
        $psi = New-Object System.Diagnostics.ProcessStartInfo
        $psi.FileName = $script:CbmExePath
        $psi.Arguments = "cli index_repository --repo-path $RepoPath --mode $script:IndexMode"
        $psi.UseShellExecute = $false
        $psi.RedirectStandardOutput = $true
        $psi.RedirectStandardError = $true
        $psi.CreateNoWindow = $true
        $psi.WindowStyle = [System.Diagnostics.ProcessWindowStyle]::Hidden

        $prevCache = $env:CBM_CACHE_DIR
        $env:CBM_CACHE_DIR = $script:CbmCacheDir
        try {
            $proc = [System.Diagnostics.Process]::Start($psi)
            if (-not $proc) {
                return @{ success = $false; channel = "exe"; error = "Process.Start 返回 null" }
            }

            # 等待进程退出（120秒超时），超时则强制终止进程树
            $completed = $proc.WaitForExit(120000)
            if (-not $completed) {
                try { $proc.Kill($true) } catch { $proc.Kill() }
                $proc.WaitForExit()
                return @{ success = $false; channel = "exe"; error = "执行超时(120s)，已强制终止进程树" }
            }

            $exitCode = $proc.ExitCode
            $stdOut = $proc.StandardOutput.ReadToEnd()
            $err    = $proc.StandardError.ReadToEnd()

            if ($exitCode -eq 0) {
                return @{ success = $true; channel = "exe"; output = $stdOut }
            } else {
                # 同时检查 stdout 中是否包含错误信息（某些情况下错误也输出到 stdout）
                if (-not $err -and $stdOut) { $err = $stdOut }
                return @{ success = $false; channel = "exe"; error = $err }
            }
        } finally {
            # 恢复父作用域环境变量原值，避免污染同一会话后续操作
            if ($null -ne $prevCache) { $env:CBM_CACHE_DIR = $prevCache }
            else { Remove-Item Env:CBM_CACHE_DIR -ErrorAction SilentlyContinue }
        }
    } catch {
        return @{ success = $false; channel = "exe"; error = $_.Exception.Message }
    }
}

# -- 扫描单个目录树 --
function Scan-DirectoryTree {
    param([string]$RootPath)

    $found = [System.Collections.Generic.List[string]]::new()

    if (-not (Test-Path $RootPath)) {
        Write-Log "目录不存在，跳过: $RootPath" "WARN"
        return $found
    }

    Write-Log "开始扫描: $RootPath (深度: $($script:ScanDepth))" "INFO"

    try {
        # 使用 -Depth 参数控制递归层数
        $gitDirs = Get-ChildItem -Path $RootPath -Recurse -Filter ".git" `
            -Directory -Depth $script:ScanDepth -ErrorAction SilentlyContinue

        foreach ($gd in $gitDirs) {
            # 从 .git 目录提取仓库根目录（使用 Parent 属性，语义安全，无硬编码长度）
            $repoRoot = $gd.Parent.FullName.TrimEnd('\', '/')
            # 路径标准化：统一解析为绝对路径（大小写、分隔符归一化），
            # 避免因路径变体导致状态文件中出现重复记录。
            # 注意：用 GetFullPath 而非 Resolve-Path —— 后者会解释通配符（* ? [ ]）
            # 和解析符号链接，含方括号的合法目录名可能导致多结果或失败。
            try { $repoRoot = [System.IO.Path]::GetFullPath($repoRoot) } catch { }

            if (Test-IgnoredPath -Path $repoRoot) {
                Write-Log "忽略匹配目录: $repoRoot" "INFO"
                $script:Result.skipped.Add($repoRoot) | Out-Null
                continue
            }

            # 验证是否为合法 git 仓库（而非空目录）
            if (-not (Test-GitRepoValid -RepoPath $repoRoot)) {
                Write-Log "跳过无效 git 仓库: $repoRoot" "INFO"
                $script:Result.skipped.Add($repoRoot) | Out-Null
                continue
            }

            $found.Add($repoRoot) | Out-Null
        }
    } catch {
        Write-Log "扫描异常 ($RootPath): $($_.Exception.Message)" "ERROR"
    }

    Write-Log "扫描完成: $RootPath, 发现 $($found.Count) 个仓库" "INFO"
    return $found
}

# -- 最小化当前 PowerShell 窗口（使用 GetConsoleWindow 替代 FindWindow） --
function Minimize-CurrentWindow {
    try {
        $code = @'
using System;
using System.Runtime.InteropServices;
public class Win32 {
    [DllImport("kernel32.dll")] public static extern IntPtr GetConsoleWindow();
    [DllImport("user32.dll")] public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);
    public const int SW_MINIMIZE = 6;
    public static void Minimize() {
        var hWnd = GetConsoleWindow();
        if (hWnd != IntPtr.Zero) ShowWindow(hWnd, SW_MINIMIZE);
    }
}
'@
        # 检查类型是否已存在（同一会话中重复调用时避免 Add-Type 冲突）
        # 注意：必须用 -as 运算符而非 [type] 'Win32' —— 后者在类型不存在时
        # 会抛异常（Unable to find type [Win32]），导致首次运行必定进入 catch，
        # Add-Type 永远不会执行，-Minimize 功能完全失效。
        if (-not ('Win32' -as [type])) {
            Add-Type -TypeDefinition $code -ErrorAction Stop
        }
        [Win32]::Minimize()
    } catch {
        Write-Log "最小化窗口失败: $($_.Exception.Message)" "DEBUG"
    }
}

# -- 输出结果（JSON 格式，供 Agent 读取） --
function Output-Result {
    $script:Result.end_time = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $script:Result.total_found = $script:Result.scanned.Count
    $script:Result.total_new = $script:Result.new_repos.Count
    $script:Result.total_reg = $script:Result.registered.Count
    $script:Result.total_fail = $script:Result.failed.Count
    $script:Result.total_skip = $script:Result.skipped.Count
    $script:Result.status = if ($script:Result.total_fail -gt 0) { "partial_success" } else { "success" }

    # 将 List 转为数组再序列化
    $output = @{
        start_time   = $script:Result.start_time
        scan_roots   = $script:Result.scan_roots
        scan_depth   = $script:Result.scan_depth
        scanned      = @($script:Result.scanned)
        new_repos    = @($script:Result.new_repos)
        registered   = @($script:Result.registered)
        failed       = @($script:Result.failed)
        skipped      = @($script:Result.skipped)
        total_found  = $script:Result.total_found
        total_new    = $script:Result.total_new
        total_reg    = $script:Result.total_reg
        total_fail   = $script:Result.total_fail
        total_skip   = $script:Result.total_skip
        end_time     = $script:Result.end_time
        duration_ms  = $script:Result.duration_ms
        status       = $script:Result.status
    }

    $json = $output | ConvertTo-Json -Depth 5 -Compress

    # 写入结果文件（带错误处理）
    try {
        Set-Content -Path $script:ResultFile -Value $json -Encoding UTF8 -ErrorAction Stop
    } catch {
        Write-Log "写入结果文件失败: $($_.Exception.Message)" "ERROR"
    }

    # 输出到 stdout（Agent 可读）
    Write-Output $json
}

# ============================================================
# █ 主程序
# ============================================================

$stopwatch = [System.Diagnostics.Stopwatch]::StartNew()

# 互斥锁：防止并发运行导致状态文件冲突
$mutex = New-Object System.Threading.Mutex($false, $script:MutexName)
$gotLock = $false
try {
    $gotLock = $mutex.WaitOne(1000)
    if (-not $gotLock) {
        Write-Log "另一个实例正在运行，本次执行退出" "WARN"
        $mutex.Dispose()
        # 输出错误结果
        @{
            status = "error"
            error  = "另一个实例正在运行，本次执行退出"
        } | ConvertTo-Json -Compress
        exit 1
    }
} catch {
    # 互斥锁创建失败不阻塞，继续执行
    Write-Log "互斥锁创建失败: $($_.Exception.Message)" "WARN"
}

try {
    # 最小化窗口
    if ($Minimize) { Minimize-CurrentWindow }

    Write-Log "=== Git 仓库扫描注册开始 ===" "INFO"
    Write-Log "扫描深度: $($script:ScanDepth), 根目录数: $($script:ScanRoots.Count)" "INFO"

    # 前置校验：检查扫描根目录是否存在
    $validRoots = @()
    foreach ($root in $script:ScanRoots) {
        if (Test-Path $root) {
            $validRoots += $root
        } else {
            Write-Log "扫描根目录不存在，跳过: $root" "WARN"
        }
    }
    if ($validRoots.Count -eq 0) {
        Write-Log "没有有效的扫描根目录，退出" "ERROR"
        $script:Result.status = "error"
        $script:Result.end_time = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        $script:Result.duration_ms = $stopwatch.ElapsedMilliseconds
        Output-Result
        exit 1
    }

    # 前置校验：ScanDepth 必须为 0-10 范围内的整数
    if ($script:ScanDepth -lt 0 -or $script:ScanDepth -gt 10) {
        Write-Log "ScanDepth 超出有效范围 (0-10): $($script:ScanDepth)" "ERROR"
        $script:Result.status = "error"
        $script:Result.end_time = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        $script:Result.duration_ms = $stopwatch.ElapsedMilliseconds
        Output-Result
        exit 1
    }

    # 加载已注册状态
    Load-RegisteredState
    Write-Log "已注册仓库数: $($script:RegisteredState.Count)" "INFO"

    # 扫描所有目录（使用 HashSet 去重，避免多根目录包含关系导致同一仓库被重复发现）
    $foundSet = [System.Collections.Generic.HashSet[string]]::new()
    $foundList = [System.Collections.Generic.List[string]]::new()
    foreach ($root in $validRoots) {
        $repos = Scan-DirectoryTree -RootPath $root
        foreach ($r in $repos) {
            if ($foundSet.Add($r)) {
                $foundList.Add($r) | Out-Null
            }
        }
    }

    $script:Result.scanned = $foundList
    Write-Log "扫描完成，共发现 $($foundList.Count) 个仓库（去重后）" "INFO"

    # 筛选新仓库
    $newRepos = [System.Collections.Generic.List[string]]::new()
    foreach ($repo in $foundList) {
        if (-not $script:RegisteredState.ContainsKey($repo)) {
            $newRepos.Add($repo) | Out-Null
        }
    }
    $script:Result.new_repos = $newRepos
    Write-Log "新仓库数: $($newRepos.Count)" "INFO"

    # 注册新仓库
    # 注意：仅注册成功时标记为已尝试，失败允许下次重试。
    # codebase-memory-mcp.exe 本身已内置去重（对已建库仓库重复调用
    # index_repository 返回 status: indexed 而非重建），因此成功标记
    # 不会导致已建库仓库被重复索引。
    foreach ($repo in $newRepos) {
        Write-Log "注册: $repo" "INFO"

        # 路径白名单校验（若配置了白名单，使用语义化子目录校验）
        if ($script:PathWhitelist.Count -gt 0) {
            $allowed = $false
            foreach ($prefix in $script:PathWhitelist) {
                if (Test-IsSubDirectory -ChildPath $repo -ParentPath $prefix) { $allowed = $true; break }
            }
            if (-not $allowed) {
                Write-Log "路径不在白名单中，拒绝注册: $repo" "WARN"
                $script:Result.failed.Add($repo) | Out-Null
                continue
            }
        }

        $regResult = Invoke-RegisterRepo -RepoPath $repo
        if ($regResult.success) {
            Write-Log "注册成功 [$($regResult.channel)]: $repo" "INFO"
            $script:Result.registered.Add($repo) | Out-Null
            # 仅成功时标记，失败允许下次重试
            $script:RegisteredState[$repo] = $true
        } else {
            Write-Log "注册失败: $($regResult.error)" "ERROR"
            $script:Result.failed.Add($repo) | Out-Null
            # 不标记已注册，下次运行会重试
        }
    }

    # 保存状态
    Save-RegisteredState

    $stopwatch.Stop()
    $script:Result.duration_ms = $stopwatch.ElapsedMilliseconds

    # 输出结果
    Output-Result

    Write-Log "=== 扫描注册完成 ($($stopwatch.ElapsedMilliseconds)ms) ===" "INFO"

    # 退出码约定（Agent 可通过 $LASTEXITCODE 判断整体结果）：
    #   0 = success（全部成功，或无新仓库需要注册）
    #   1 = partial_success（有仓库注册失败，但至少部分成功）
    #   2 = error（前置校验失败、无有效根目录等）
    if ($script:Result.status -eq "partial_success") {
        exit 1
    } elseif ($script:Result.status -eq "error") {
        exit 2
    }

} finally {
    # 释放互斥锁
    if ($gotLock) {
        try { $mutex.ReleaseMutex() } catch {}
    }
    $mutex.Dispose()
}
