name: Pre-release

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - release-please-*

jobs:
  pre-release:
    name: 'Verify artifacts before release'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 2
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: npm
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Build and bundle
        run: npm run bundle
        env:
          NODE_ENV: 'production'

      - name: Verify server.json
        run: npm run verify-server-json-version

      - name: Verify npm package
        run: npm run verify-npm-package
